# fly.toml app configuration file generated for pocketbase-thrumming-resonance-8731 on 2024-11-24T14:42:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fich-ar'
primary_region = 'eze'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"
